export const ROUTES = {
  SIGNIN: '/signin',
  SIGNIN_AGREEMENT: '/signin/agreement',
  SIGNUP: '/signup',
  SIGNUP_SUCCESS: 'signup/success',
  POINT_DETAIL: '/point-detail',
  INIT: '/init',
  INIT_ACCOMMODATION_REGISTRATION: '/init/accommodation-registration',
  INIT_ROOM_REGISTRATION: '/init/room-registration',
  INIT_INFO_CONFIRMATION: '/init/info-confirmation',
  COUPON: '/coupon',
  COUPON_REGISTRATION: '/coupon/registration',
  MAIN: '/',
  ROOM: '/room',
  ROOM_REGISTRATION: '/room/registration',
  ROOM_UPDATE: '/room/update',
};
